baseURL = "http://web.infenlaces.com/distancia/presentacion/"
languageCode = "en-us"
title = "Presentación ciclo distancia"
disableKinds = ["sitemap", "RSS"]
theme = "github.com/dzello/reveal-hugo"
# theme = "."
# themesDir = "../"

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true
enableEmoji = true

[params.logo]
src = "images/logo.png"

[params.author]
name = "Manuel Romero"

# currently only the unsafe mode for goldmark is supported

[markup.goldmark]
     [markup.goldmark.renderer]
       unsafe = true

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
codeFences = false  # use highlight.js
# codeFences = true  # use hugo highlighting at compile time
style = "tango"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"

[module]
  # needs hugo v0.109.0 or higher and go 1.18 or higher:
  # uncomment line below for local development of module
  # workspace = "hugo.work"
